name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.26.0"

      - name: Create unitypackage
        run: deno run -A .scripts/create-unitypackage.ts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ".release/*"
